export const GET_PERSONS = "GET_PERSONS";
export const DELETE_PERSON = "DELETE_PERSON";
export const ADD_PERSON = "ADD_PERSON";
export const UPDATE_PERSON = "UPDATE_PERSON";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const STORAGE_PERSON = "STORAGE_PERSON";
export const REQUEST_SUCCES = "REQUEST_SUCCES";
export const REQUEST_CONFIRM = "REQUEST_CONFIRM";